### ISSUE TITLE
Make it more configurable!

### ISSUE THREAD

**Issue by alietors** [ejosafat/random-bonusly#1]
- Accepting number of points as parameter
- Configurable fortune db
- Hashtags
...

**Comment by ejosafat** [comment]
All of that is in the roadmap (I'll create a wiki page for it soon), thanks for your input.

**Comment by ejosafat** [comment]
You can now specify which set(s) of fortune you want to use, just add them at the end of the command line invocation (you can see an example in the README).

**Comment by ejosafat** [comment]
You now got also points, hashtags and messages :-)
